apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasMigration
metadata:
  name: backend-migration
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  credentials:
    scheme: postgres
    host: "6ea7e9f2efe1.3saucev2x125n.asia-northeast2.sql.goog"
    port: 5432
    user: postgres
    passwordFrom:
      secretKeyRef:
        name: atlas-db-credentials
        key: postgres-admin-password
    database: liverty-music
    parameters:
      sslmode: disable
  dir:
    configMapRef:
      name: atlas-migration-dir
