apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    group: db.atlasgo.io
    version: v1alpha1
    kind: AtlasMigration
    name: backend-migration
  patch: |
    - op: replace
      path: /spec/credentials/host
      value: "6ea7e9f2efe1.3saucev2x125n.asia-northeast2.sql.goog"
